export const contentFields = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['content'] } },
		options: [
			{ name: 'Create', value: 'create', description: 'Create new content' },
			{ name: 'Get by ID', value: 'getById', description: 'Get content by ID' },
			{
				name: 'Find by Content Pool',
				value: 'findByContentPool',
				description: 'Find contents by content pool',
			},
			{ name: 'Find by Group', value: 'findByGroup', description: 'Find contents by group' },
			{
				name: 'Find by Orgunit',
				value: 'findByOrgunit',
				description: 'Find contents by organization unit',
			},
			{ name: 'Update by ID', value: 'updateById', description: 'Update content by ID' },
			{ name: 'Delete', value: 'delete', description: 'Delete content by ID' },
		],
		default: 'create',
	},
	{
		displayName: 'Content ID',
		name: 'contentId',
		type: 'string',
		displayOptions: {
			show: { resource: ['content'], operation: ['getById', 'updateById', 'delete'] },
		},
		default: '',
		placeholder: '63bd885034d0466d11073575',
		description: 'The ID of the content',
		required: true,
	},
	{
		displayName: 'Define',
		name: 'defineContentInput',
		type: 'options',
		displayOptions: { show: { resource: ['content'], operation: ['create'] } },
		options: [{ name: 'Using JSON', value: 'json' }],
		default: 'json',
		description: 'Modify JSON body per your needs.',
	},
	{
		displayName: 'JSON Body',
		name: 'contentBody',
		type: 'json',
		displayOptions: {
			show: { resource: ['content'], operation: ['create'], defineContentInput: ['json'] },
		},
		default: '{}',
		required: true,
		placeholder: '{"originLanguage":"en",...}',
	},
	{
		displayName: 'Content Pool ID',
		name: 'filterContentPoolId',
		type: 'string',
		displayOptions: { show: { resource: ['content'], operation: ['findByContentPool'] } },
		default: '',
		placeholder: '63bd885034d0466d11073575',
		description: 'Content pool ID to filter by',
		required: true,
	},
	{
		displayName: 'Group ID',
		name: 'groupId',
		type: 'string',
		displayOptions: { show: { resource: ['content'], operation: ['findByGroup'] } },
		default: '',
		placeholder: 'group-id',
		description: 'Group ID to filter by',
		required: true,
	},
	{
		displayName: 'Orgunit ID',
		name: 'orgunitId',
		type: 'string',
		displayOptions: { show: { resource: ['content'], operation: ['findByOrgunit'] } },
		default: '',
		placeholder: 'orgunit-id',
		description: 'Organization unit ID to filter by',
		required: true,
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		displayOptions: {
			show: {
				resource: ['content'],
				operation: ['findByContentPool', 'findByGroup', 'findByOrgunit'],
			},
		},
		default: 50,
		description: 'Maximum number of results to return',
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'assignmentCollection',
		typeOptions: {
			assignmentLimit: 100,
			fields: [
				{ displayName: 'Field Name', name: 'name', type: 'string' },
				{ displayName: 'Field Value', name: 'value', type: 'string' },
			],
		},
		displayOptions: { show: { resource: ['content'], operation: ['updateById'] } },
		default: {},
	},
];
