import type { INodeProperties } from 'n8n-workflow';

export const contentFields: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['content'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				description: 'Create new content',
				action: 'Create content',
			},
			{
				name: 'Delete',
				value: 'delete',
				description: 'Delete content by ID',
				action: 'Delete content',
			},
			{
				name: 'Find by Content Pool',
				value: 'findByContentPool',
				description: 'Find contents by content pool',
				action: 'Find content by content pool',
			},
			{
				name: 'Find by Group',
				value: 'findByGroup',
				description: 'Find contents by group',
				action: 'Find content by group',
			},
			{
				name: 'Find by Orgunit',
				value: 'findByOrgunit',
				description: 'Find contents by organization unit',
				action: 'Find content by orgunit',
			},
			{
				name: 'Get by ID',
				value: 'getById',
				description: 'Get content by ID',
				action: 'Get content by ID',
			},
			{
				name: 'Update by ID',
				value: 'updateById',
				description: 'Update content by ID',
				action: 'Update content by ID',
			},
		],

		default: 'create',
	},
	{
		displayName: 'Content ID',
		name: 'contentId',
		type: 'string',
		displayOptions: {
			show: { resource: ['content'], operation: ['getById', 'updateById', 'delete'] },
		},
		default: '',
		placeholder: '63bd885034d0466d11073575',
		description: 'The ID of the content',
		required: true,
	},
	{
		displayName: 'Define',
		name: 'defineContentInput',
		type: 'options',
		displayOptions: { show: { resource: ['content'], operation: ['create'] } },
		options: [{ name: 'Using JSON', value: 'json' }],
		default: 'json',
		description: 'Modify JSON body per your needs',
	},
	{
		displayName: 'JSON Body',
		name: 'contentBody',
		type: 'json',
		displayOptions: {
			show: {
				resource: ['content'],
				operation: ['create'],
				defineContentInput: ['json'],
			},
		},
		default: JSON.stringify(
			{
				originLanguage: 'en/nl',
				contentType: 'add content type',
				contentPool: 'YOUR_POOL_ID',
				title: { en: 'Your Title' },
				message: { en: '<p>Your message</p>' },
				private: false,
				sendPushNotification: false,
				notifyNew: false,
				notifyOnAttendeeActions: false,
				notifyAttendeesOnUpdate: false,
				highlighted: false,
				tags: [],
				mentions: [],
				relatedTags: [],
				social: { reactionsEnabled: true, commentsEnabled: true },
				form: {
					active: true,
					anonymous: false,
					confidential: false,
					confidants: [],
					emails: [''],
					fields: [],
					shareable: false,
				},
				event: {
					widgets: [],
					attendanceType: 'n/a',
					endDate: null,
					deactivationDate: null,
				},
				training: { lessons: [] },
				translationRequest: [],
				status: 'n/a',
				orgchartSelection: { include: ['root0001'], exclude: [] },
				orgchartAttrSelection: { include: [], exclude: [] },
				groups: { selection: [], exclude: false },
				orgunits: [],
			},
			null,
			2,
		),
		required: true,
		placeholder: '{"originLanguage":"en",...}',
		description:
			'Complete JSON body for creating Keephub content. See <a href="https://dev.api.keephub.io/api-docs/" target="_blank">API documentation</a> for all available fields.',
	},
	{
		displayName: 'Content Pool ID',
		name: 'filterContentPoolId',
		type: 'string',
		displayOptions: { show: { resource: ['content'], operation: ['findByContentPool'] } },
		default: '',
		placeholder: '63bd885034d0466d11073575',
		description: 'Content pool ID to filter by',
		required: true,
	},
	{
		displayName: 'Group ID',
		name: 'groupId',
		type: 'string',
		displayOptions: { show: { resource: ['content'], operation: ['findByGroup'] } },
		default: '',
		placeholder: 'group-ID',
		description: 'Group ID to filter by',
		required: true,
	},
	{
		displayName: 'Orgunit ID',
		name: 'orgunitId',
		type: 'string',
		displayOptions: { show: { resource: ['content'], operation: ['findByOrgunit'] } },
		default: '',
		placeholder: 'orgunit-ID',
		description: 'Organization unit ID to filter by',
		required: true,
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'assignmentCollection',
		typeOptions: {
			assignmentLimit: 100,
			fields: [
				{ displayName: 'Field Name', name: 'name', type: 'string', default: '' },
				{ displayName: 'Field Value', name: 'value', type: 'string', default: '' },
			],
		},
		displayOptions: { show: { resource: ['content'], operation: ['updateById'] } },
		default: {},
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		displayOptions: {
			show: {
				resource: ['content'],
				operation: ['findByContentPool', 'findByGroup', 'findByOrgunit'],
			},
		},
		default: {},
		placeholder: 'Add option',
		options: [
			{
				displayName: 'Limit',
				name: 'limit',
				type: 'number',
				typeOptions: {
					minValue: 1,
				},
				default: 50,
				description: 'Max number of results to return',
			},
			{
				displayName: 'Skip',
				name: 'skip',
				type: 'number',
				default: 0,
				description: 'Number of results to skip (pagination)',
			},
			{
				displayName: 'Sort Field',
				name: 'sortBy',
				type: 'string',
				default: '',
				placeholder: 'createdAt',
				description: 'Field to sort by',
			},
			{
				displayName: 'Sort Order',
				name: 'sortOrder',
				type: 'options',
				options: [
					{ name: 'Ascending', value: 1 },
					{ name: 'Descending', value: -1 },
				],
				default: 1,
			},
		],
	},
]
