import type { INodeProperties } from 'n8n-workflow';

export const taskFields: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['task'] } },
		options: [
			{
				name: 'Create',
				value: 'createTask',
				description: 'Create a new task template',
				action: 'Create a task template',
			},
			{
				name: 'Delete',
				value: 'deleteTask',
				description: 'Delete a task template',
				action: 'Delete a task template',
			},
			{
				name: 'Get by ID',
				value: 'getTask',
				description: 'Get a task template by ID',
				action: 'Get a task by ID',
			},
			{
				name: 'Get By Orgunit',
				value: 'getTaskByOrgunit',
				description: 'Get tasks by orgunit',
				action: 'Get tasks by orgunit',
			},
			{
				name: 'Get Progress',
				value: 'getTaskProgress',
				description: 'Get task template progress',
				action: 'Get progress for a task template',
			},
			{
				name: 'Get Status Counts',
				value: 'getTaskStatusCounts',
				description: 'Get task template status counts',
				action: 'Get status counts for a task template',
			},
		],

		default: 'createTask',
	},
	{
		displayName: 'Define',
		name: 'defineTaskInput',
		type: 'options',
		displayOptions: { show: { resource: ['task'], operation: ['createTask'] } },
		options: [
			{ name: 'Using Fields Below', value: 'fields' },
			{ name: 'Using JSON', value: 'json' },
		],
		default: 'fields',
		description: 'How to define the task to create',
	},
	{
		displayName: 'JSON Body',
		name: 'taskJsonBody',
		type: 'json',
		displayOptions: {
			show: { resource: ['task'], operation: ['createTask'], defineTaskInput: ['json'] },
		},
		default: '{}',
		placeholder: '{"title":{"en":"Task"},"template":{"form":{"fields":[]}}}',
		description: 'Complete JSON body for task creation',
		required: true,
	},
	{
		displayName: 'Task ID',
		name: 'taskId',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['task'],
				operation: ['getTask', 'deleteTask', 'getTaskProgress', 'getTaskStatusCounts'],
			},
		},
		default: '',
		placeholder: '63bd885034d0466d11073575',
		description: 'The ID of the task',
		required: true,
	},
	{
		displayName: 'Title',
		name: 'taskTitle',
		type: 'string',
		displayOptions: {
			show: { resource: ['task'], operation: ['createTask'], defineTaskInput: ['fields'] },
		},
		default: '',
		placeholder: 'Task title',
		description: 'Title of the task',
		required: true,
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: { resource: ['task'], operation: ['createTask'], defineTaskInput: ['fields'] },
		},
		options: [
			{
				displayName: 'Message',
				name: 'taskMessage',
				type: 'string',
				typeOptions: { rows: 4 },
				default: '',
				placeholder: 'Task description',
				description: 'Message for the task',
			},
			{
				displayName: 'Send Notification',
				name: 'taskNotification',
				type: 'boolean',
				default: false,
				description: 'Whether to send notifications',
			},
			{
				displayName: 'Timezone',
				name: 'timezone',
				type: 'string',
				default: 'Europe/Amsterdam',
				placeholder: 'Europe/Amsterdam',
				description: 'IANA timezone for the task schedule (e.g. Europe/London, America/New_York)',
			},
		],
	},
	{
		displayName: 'Orgunit ID',
		name: 'orgunitId',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['task'],
				operation: ['getTaskByOrgunit'],
			},
		},
		default: '',
		placeholder: 'root0077',
		description: 'Orgunit ID to filter tasks by',
		required: true,
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		displayOptions: {
			show: {
				resource: ['task'],
				operation: ['getTaskByOrgunit'],
			},
		},
		default: {},
		noDataExpression: true,
		placeholder: 'Add option',
		options: [
			{
				displayName: 'Limit',
				name: 'limit',
				type: 'number',
				typeOptions: { minValue: 1 },
				default: 50,
				description: 'Max number of results to return',
			},
			{
				displayName: 'Skip',
				name: 'skip',
				type: 'number',
				default: 0,
				description: 'Number of results to skip (pagination)',
			},
			{
				displayName: 'Sort Field',
				name: 'sortBy',
				type: 'string',
				default: '',
				placeholder: 'template.dueDate',
				description: 'Field you wish to sort by should be preceded with "template." (example: template.title)',
			},
			{
				displayName: 'Sort Order',
				name: 'sortOrder',
				type: 'options',
				options: [
					{ name: 'Ascending', value: 1 },
					{ name: 'Descending', value: -1 },
				],
				default: 1,
			},
			{
				displayName: 'Start Date After',
				name: 'startDateGte',
				type: 'dateTime',
				default: '',
				description: 'Filter tasks with start date after this date',
			},
			{
				displayName: 'Start Date Before',
				name: 'startDateLte',
				type: 'dateTime',
				default: '',
				description: 'Filter tasks with start date before this date',
			},
		],
	},
];
