import type { INodeProperties } from 'n8n-workflow';

export const userFields: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['user'] } },
		options: [
			{
				name: 'Get by ID',
				value: 'getById',
				description: 'Retrieve a user by their unique ID',
				action: 'Get a user by ID',
			},
			{
				name: 'Find by Login Name',
				value: 'findByLoginName',
				description: 'Retrieve a user by their Login Name',
				action: 'Find a user by login name',
			},
			{
				name: 'Find by Group',
				value: 'findByGroup',
				description: 'Find all users in a specific group',
				action: 'Find a user by group',
			},
			{
				name: 'Find by Orgunit',
				value: 'findByOrgunit',
				description: 'Find all users in a specific organization unit',
				action: 'Find a user by orgunit',
			},
		],
		default: 'getById',
	},
	{
		displayName: 'User ID',
		name: 'userId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['user'], operation: ['getById'] } },
		placeholder: '63bd885034d0466d11073575',
		description: 'The unique identifier of the user',
		default: '',
	},
	{
		displayName: 'Login Name',
		name: 'loginName',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['user'], operation: ['findByLoginName'] } },
		placeholder: 'john.doe',
		description: 'Login Name to search for',
		default: '',
	},
	{
		displayName: 'Group ID',
		name: 'groupId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['user'], operation: ['findByGroup'] } },
		placeholder: 'groupId',
		description: 'Group ID to filter users by',
		default: '',
	},
	{
		displayName: 'Orgunit ID',
		name: 'orgunitId',
		type: 'string',
		required: true,
		displayOptions: { show: { resource: ['user'], operation: ['findByOrgunit'] } },
		placeholder: 'root0001',
		description: 'Organization unit ID to filter users by',
		default: '',
	},
];
